#!/bin/sh

python3 separateResultsPerQuery.py fold_1/predictions_SORTED.pred fold_1/query1_predictions_SORTED.pred 1
python3 separateResultsPerQuery.py fold_1/predictions_SORTED.pred fold_1/query2_predictions_SORTED.pred 2
python3 separateResultsPerQuery.py fold_1/predictions_SORTED.pred fold_1/query3_predictions_SORTED.pred 3
python3 separateResultsPerQuery.py fold_1/predictions_SORTED.pred fold_1/query4_predictions_SORTED.pred 4
python3 separateResultsPerQuery.py fold_1/predictions_SORTED.pred fold_1/query5_predictions_SORTED.pred 5
python3 separateResultsPerQuery.py fold_1/predictions_SORTED.pred fold_1/query6_predictions_SORTED.pred 6
python3 separateResultsPerQuery.py fold_1/predictions_SORTED.pred fold_1/query7_predictions_SORTED.pred 7
python3 separateResultsPerQuery.py fold_1/predictions_SORTED.pred fold_1/query8_predictions_SORTED.pred 8
python3 separateResultsPerQuery.py fold_1/predictions_SORTED.pred fold_1/query9_predictions_SORTED.pred 9
python3 separateResultsPerQuery.py fold_1/predictions_SORTED.pred fold_1/query10_predictions_SORTED.pred 10

python3 separateResultsPerQuery.py fold_2/predictions_SORTED.pred fold_2/query11_predictions_SORTED.pred 11
python3 separateResultsPerQuery.py fold_2/predictions_SORTED.pred fold_2/query12_predictions_SORTED.pred 12
python3 separateResultsPerQuery.py fold_2/predictions_SORTED.pred fold_2/query13_predictions_SORTED.pred 13
python3 separateResultsPerQuery.py fold_2/predictions_SORTED.pred fold_2/query14_predictions_SORTED.pred 14
python3 separateResultsPerQuery.py fold_2/predictions_SORTED.pred fold_2/query15_predictions_SORTED.pred 15
python3 separateResultsPerQuery.py fold_2/predictions_SORTED.pred fold_2/query16_predictions_SORTED.pred 16
python3 separateResultsPerQuery.py fold_2/predictions_SORTED.pred fold_2/query17_predictions_SORTED.pred 17
python3 separateResultsPerQuery.py fold_2/predictions_SORTED.pred fold_2/query18_predictions_SORTED.pred 18
python3 separateResultsPerQuery.py fold_2/predictions_SORTED.pred fold_2/query19_predictions_SORTED.pred 19
python3 separateResultsPerQuery.py fold_2/predictions_SORTED.pred fold_2/query20_predictions_SORTED.pred 20

python3 separateResultsPerQuery.py fold_3/predictions_SORTED.pred fold_3/query21_predictions_SORTED.pred 21
python3 separateResultsPerQuery.py fold_3/predictions_SORTED.pred fold_3/query22_predictions_SORTED.pred 22
python3 separateResultsPerQuery.py fold_3/predictions_SORTED.pred fold_3/query23_predictions_SORTED.pred 23
python3 separateResultsPerQuery.py fold_3/predictions_SORTED.pred fold_3/query24_predictions_SORTED.pred 24
python3 separateResultsPerQuery.py fold_3/predictions_SORTED.pred fold_3/query25_predictions_SORTED.pred 25
python3 separateResultsPerQuery.py fold_3/predictions_SORTED.pred fold_3/query26_predictions_SORTED.pred 26
python3 separateResultsPerQuery.py fold_3/predictions_SORTED.pred fold_3/query27_predictions_SORTED.pred 27
python3 separateResultsPerQuery.py fold_3/predictions_SORTED.pred fold_3/query28_predictions_SORTED.pred 28
python3 separateResultsPerQuery.py fold_3/predictions_SORTED.pred fold_3/query29_predictions_SORTED.pred 29
python3 separateResultsPerQuery.py fold_3/predictions_SORTED.pred fold_3/query30_predictions_SORTED.pred 30

python3 separateResultsPerQuery.py fold_4/predictions_SORTED.pred fold_4/query31_predictions_SORTED.pred 31
python3 separateResultsPerQuery.py fold_4/predictions_SORTED.pred fold_4/query32_predictions_SORTED.pred 32
python3 separateResultsPerQuery.py fold_4/predictions_SORTED.pred fold_4/query33_predictions_SORTED.pred 33
python3 separateResultsPerQuery.py fold_4/predictions_SORTED.pred fold_4/query34_predictions_SORTED.pred 34
python3 separateResultsPerQuery.py fold_4/predictions_SORTED.pred fold_4/query35_predictions_SORTED.pred 35
python3 separateResultsPerQuery.py fold_4/predictions_SORTED.pred fold_4/query36_predictions_SORTED.pred 36
python3 separateResultsPerQuery.py fold_4/predictions_SORTED.pred fold_4/query37_predictions_SORTED.pred 37
python3 separateResultsPerQuery.py fold_4/predictions_SORTED.pred fold_4/query38_predictions_SORTED.pred 38
python3 separateResultsPerQuery.py fold_4/predictions_SORTED.pred fold_4/query39_predictions_SORTED.pred 39
python3 separateResultsPerQuery.py fold_4/predictions_SORTED.pred fold_4/query40_predictions_SORTED.pred 40

python3 separateResultsPerQuery.py fold_5/predictions_SORTED.pred fold_5/query41_predictions_SORTED.pred 41
python3 separateResultsPerQuery.py fold_5/predictions_SORTED.pred fold_5/query42_predictions_SORTED.pred 42
python3 separateResultsPerQuery.py fold_5/predictions_SORTED.pred fold_5/query43_predictions_SORTED.pred 43
python3 separateResultsPerQuery.py fold_5/predictions_SORTED.pred fold_5/query44_predictions_SORTED.pred 44
python3 separateResultsPerQuery.py fold_5/predictions_SORTED.pred fold_5/query45_predictions_SORTED.pred 45
python3 separateResultsPerQuery.py fold_5/predictions_SORTED.pred fold_5/query46_predictions_SORTED.pred 46
python3 separateResultsPerQuery.py fold_5/predictions_SORTED.pred fold_5/query47_predictions_SORTED.pred 47
python3 separateResultsPerQuery.py fold_5/predictions_SORTED.pred fold_5/query48_predictions_SORTED.pred 48
python3 separateResultsPerQuery.py fold_5/predictions_SORTED.pred fold_5/query49_predictions_SORTED.pred 49
python3 separateResultsPerQuery.py fold_5/predictions_SORTED.pred fold_5/query50_predictions_SORTED.pred 50

python3 separateResultsPerQuery.py fold_6/predictions_SORTED.pred fold_6/query51_predictions_SORTED.pred 51
python3 separateResultsPerQuery.py fold_6/predictions_SORTED.pred fold_6/query52_predictions_SORTED.pred 52
python3 separateResultsPerQuery.py fold_6/predictions_SORTED.pred fold_6/query53_predictions_SORTED.pred 53
python3 separateResultsPerQuery.py fold_6/predictions_SORTED.pred fold_6/query54_predictions_SORTED.pred 54
python3 separateResultsPerQuery.py fold_6/predictions_SORTED.pred fold_6/query55_predictions_SORTED.pred 55
python3 separateResultsPerQuery.py fold_6/predictions_SORTED.pred fold_6/query56_predictions_SORTED.pred 56
python3 separateResultsPerQuery.py fold_6/predictions_SORTED.pred fold_6/query57_predictions_SORTED.pred 57
python3 separateResultsPerQuery.py fold_6/predictions_SORTED.pred fold_6/query58_predictions_SORTED.pred 58
python3 separateResultsPerQuery.py fold_6/predictions_SORTED.pred fold_6/query59_predictions_SORTED.pred 59
python3 separateResultsPerQuery.py fold_6/predictions_SORTED.pred fold_6/query60_predictions_SORTED.pred 60
